name: Dry run - Deploy Smoke test job to staging
on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Docker build and push
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ubuntu-latest
    steps:
      - name: check1
        run: |
          echo "arjun2"
          echo ${{ matrix.os }} 

  deploy-smoke-test-job:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Deploy Smoke Test Job to Staging
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout2
        run: |
          echo "arjun2"
