name: Dry run - Deploy Smoke test job to staging
on:
  push:
    branches: [ change-to-main ]

jobs:
  docker-build:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      - name: check1
       run: |
          echo "arjun1"

  deploy-smoke-test-job:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Deploy Smoke Test Job to Staging
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout2
        run: |
          echo "arjun2"
